### ISSUE TITLE
Upstream the kernel source code

### ISSUE THREAD

**Issue by rifsxd** [realme-kernel-opensource/realme_C31_C33_C35_narzo50A-Prime-AndroidT-kernel-source#1]
Please maintain the repository and upstream the kernel source code and if you wont update then atleast fix the bugs which makes it to fail compiling

**Comment by realme-kernel-opensource** [comment]
> Please maintain the repository and upstream the kernel source code and if you wont update then atleast fix the bugs which makes it to fail compiling

Dear Customer,
If there are any compilation issues, please provide log to us via email: [realme-kernel-opensource@realme.com]. Thanks.

**Comment by rifsxd** [comment]
> > Please maintain the repository and upstream the kernel source code and if you wont update then atleast fix the bugs which makes it to fail compiling
> 
> Dear Customer, If there are any compilation issues, please provide log to us via email: [[realme-kernel-opensource@realme.com](mailto:realme-kernel-opensource@realme.com)]. Thanks.

Can you please update the source upto 5.4.254 which is the latest update provided by ota updates, cuz the source code 5.4 210 which is old, thanks

**Comment by realme-kernel-opensource** [comment]
> > > Please maintain the repository and upstream the kernel source code and if you wont update then atleast fix the bugs which makes it to fail compiling
> > 
> > 
> > Dear Customer, If there are any compilation issues, please provide log to us via email: [[realme-kernel-opensource@realme.com](mailto:realme-kernel-opensource@realme.com)]. Thanks.
> 
> Can you please update the source upto 5.4.254 which is the latest update provided by ota updates, cuz the source code 5.4 210 which is old, thanks

Please get it from: https://github.com/realme-kernel-opensource/realme_C31_C33_C35_narzo50A-Prime-AndroidT-NEW-kernel-source, thanks.

**Comment by rifsxd** [comment]
Thanks a lot 🙏
